- type: entity
  id: BaseMindRole
  name: Mind Role
  description: Mind Role entity
  abstract: true
  components:
  - type: MindRole

#Observer
- type: entity
  parent: BaseMindRole
  id: MindRoleObserver
  name: Observer Role
  components:
  - type: ObserverRole
  - type: MindRole
    sortWeight: -10

#Ghost Roles
- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleNeutral
  name: Ghost Role
  components:
  - type: GhostRoleMarkerRole

# The Job MindRole holds the mob's Job prototype
- type: entity
  parent: BaseMindRole
  id: MindRoleJob
  name: Job Role
  # JobPrototype is filled by SharedJobSystem


- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleFreeAgent
  name: Ghost Role (Free Agent)
  components:
  - type: MindRole
    roleType: FreeAgent
    sortWeight: 0 # Maybe 10?

- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostRoleSilicon
  name: Ghost Role (Silicon)
  components:
  - type: MindRole
    roleType: Silicon

# Silicon
- type: entity
  parent: BaseMindRole
  id: MindRoleSiliconBrain
  name: Borg Brain Role
  components:
  - type: MindRole
    roleType: Silicon
  - type: SiliconBrainRole
