- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 5h
  weight: 10
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false
